In [1]:
import os
import re
import unicodedata
import pandas as pd
import numpy as np
from IPython.display import display

pd.set_option("display.max_colwidth", 120)
pd.set_option("display.max_columns", 100)

In [ ]:
def find_csv_by_name(filename, search_root="/kaggle/input"):
    """Tìm file CSV theo tên trong thư mục Kaggle input."""
    for root, dirs, files in os.walk(search_root):
        if filename in files:
            return os.path.join(root, filename)
    return None


# Nếu chạy trên Kaggle
products_path = find_csv_by_name("shopee_products_clean.csv")
reviews_path = find_csv_by_name("shopee_reviews_clean.csv")

if products_path is None:
    products_path = "shopee_products_clean.csv"

if reviews_path is None:
    reviews_path = "shopee_reviews_clean.csv"

print("Products path:", products_path)
print("Reviews path:", reviews_path)

Products path: /kaggle/input/datasets/thuyvanne/review-shoppe/shopee_products_clean.csv
Reviews path: /kaggle/input/datasets/thuyvanne/review-shoppe/shopee_reviews_clean.csv

In [3]:
products = pd.read_csv(products_path)
reviews = pd.read_csv(reviews_path)

print("Products shape:", products.shape)
print("Reviews shape:", reviews.shape)

display(products.head())
display(reviews.head())

Products shape: (347, 17)
Reviews shape: (8992, 14)

,shop,shop_id,item_id,product_name,current_price,original_price,discount_percent,rating,rating_count,sold_count,monthly_sold,liked_count,brand,product_url,product_name_clean,sold_count_num,monthly_sold_num
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",880000.0,880000.0,0,5.000000,"[3, 0, 0, 0, 0, 3]",889 đã bán,808 đã bán/tháng,59,Xiaomi,https://shopee.vn/product/340431675/28914299334,đồng hồ thông minh redmi watch 5 active màn hình lcd 2 l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,889,808
1,xiaomiofficialstore,340431675,27514293609,"Đồng hồ thông minh Redmi Watch 5 Lite | Màn hình AMOLED 2"" l Nghe gọi Bluetooth | +150 chế độ thể thao | 5ATM | GPS/...",1390000.0,1390000.0,0,3.833333,"[6, 1, 0, 1, 1, 3]",31 đã bán,1 đã bán/tháng,35,Xiaomi,https://shopee.vn/product/340431675/27514293609,đồng hồ thông minh redmi watch 5 lite màn hình amoled 2 l nghe gọi bluetooth +150 chế độ thể thao 5atm gps/gnss,31,1
2,xiaomiofficialstore,340431675,48656445603,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",9490000.0,10990000.0,14,4.956757,"[185, 1, 0, 0, 4, 180]",533 đã bán,191 đã bán/tháng,511,Xiaomi,https://shopee.vn/product/340431675/48656445603,"pre-order điện thoại poco x8 pro 5g 8+256gb 8+512gb 12+512gb màn 6.59 1,5k 120hz d8500u 50mp",533,191
3,xiaomiofficialstore,340431675,26262566585,Sạc Xiaomi 67W HyperCharge Combo (Type-A) EU,890000.0,890000.0,0,4.924051,"[79, 1, 0, 0, 2, 76]",366 đã bán,181 đã bán/tháng,78,Xiaomi,https://shopee.vn/product/340431675/26262566585,sạc xiaomi 67w hypercharge combo type-a eu,366,181
4,xiaomiofficialstore,340431675,26221234933,"[Livestream] Điện thoại POCO X7 Pro 5G (8+256GB | 12+256GB) | Màn 6.67"" 120Hz AMOLED | D8400-Ultra",10690000.0,10690000.0,0,4.941467,"[1418, 5, 2, 9, 39, 1363]",5k+ đã bán,1k+ đã bán/tháng,1760,Poco,https://shopee.vn/product/340431675/26221234933,livestream điện thoại poco x7 pro 5g 8+256gb 12+256gb màn 6.67 120hz amoled d8400-ultra,5000,1000

,shop,shop_id,item_id,product_name,product_url,review_text,review_star,author_username,ctime,model_name,liked_count,review_text_clean,sentiment_by_star,review_star_group
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Giao hàngg nhanh, dùngg khá ổn shop có tư vấn. Mua được giá rẻe.",5,doyen9,1768667109,Đen,NaN,"giao hàngg nhanh, dùngg khá ổn shop có tư vấn. mua được giá rẻe.",positive,5 sao
1,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:Redmi Active 5\nChất lượng sản phẩm:Mình đánh giá sau\n\nRedmi Active 5.\nDo hết hàng nên mình đợi kh...,5,dthang92,1765961178,Bạc,NaN,đúng với mô tả:redmi active 5 chất lượng sản phẩm:mình đánh giá sau redmi active 5. do hết hàng nên mình đợi khá lâu...,positive,5 sao
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",5,p*****f,1767692199,Đen,NaN,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",positive,5 sao
3,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:ok\nChất lượng sản phẩm:ok\n\nsp khá ổn trong tầm giá,5,b*****0,1764553050,Bạc,NaN,đúng với mô tả:ok chất lượng sản phẩm:ok sp khá ổn trong tầm giá,positive,5 sao
4,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Giao hàng nhanh chóng. Hình ảnh và video mang tính chất nhận xu.,5,d*****7,1769928670,Đen,NaN,giao hàng nhanh chóng. hình ảnh và video mang tính chất nhận xu.,positive,5 sao

In [4]:
SHOP_NAME_MAP = {
    "xixiaomiofficialstore": "xiaomiofficialstore",
    "sốshopdunk_official_store": "shopdunk_official_store",
    "Ushopdunk_official_store": "shopdunk_official_store",
    "sshopdunk_official_store": "shopdunk_official_store",
}

products["shop_clean"] = products["shop"].replace(SHOP_NAME_MAP)
reviews["shop_clean"] = reviews["shop"].replace(SHOP_NAME_MAP)

# Ép kiểu số cho các cột cần dùng sau này
numeric_cols = [
    "current_price", "original_price", "discount_percent",
    "rating", "rating_count", "sold_count_num",
    "monthly_sold_num", "liked_count"
]

for col in numeric_cols:
    if col in products.columns:
        products[col] = pd.to_numeric(products[col], errors="coerce")

if "review_star" in reviews.columns:
    reviews["review_star"] = pd.to_numeric(reviews["review_star"], errors="coerce")

print("Shop after cleaning:")
display(products["shop_clean"].value_counts())

Shop after cleaning:

shop_clean
samsung_official_store     41
xiaomiofficialstore        39
viettel_store_aar          36
oppo_official_store_vn     34
huawei_flagship_store      33
apple_flagship_store       30
minhtuanmobile.official    30
didongviet.official        29
tecno_official_store       28
shopdunk_official_store    27
vivo_vietnam               14
realmevietnam               6
Name: count, dtype: int64

In [5]:
NOISE_PHRASES = [
    # quảng cáo / trạng thái bán
    "hàng chính hãng", "hàng chính hãng", "chính hãng", "chính hãng",
    "livestream", "live stream", "live", "ls",
    "ưu đãi livestream", "ưu đãi ls", "ưu đãi", "voucher 200k", "voucher",
    "pre order", "pre-order", "preorder", "coming soon", "độc quyền",
    "kol", "ddv x hannah", "mới", "new",

    # quà tặng / combo
    "hàng tặng không bán", "hàng tặng",
    "quà tặng không bán", "quà tặng màu ngẫu nhiên",
    "quà tặng ngẫu nhiên", "quà tặng",
    "không bán lẻ", "tặng kèm", "combo",

    # bảo hành / cam kết
    "1 đổi 1 trong tháng đầu tiên",
    "1 đổi 1 tháng đầu tiên",
    "1 đổi 1",
    "tháng đầu tiên",
    "bảo hành chính hãng 12 tháng",
    "bảo hành chính hãng 18 tháng",
    "bảo hành 12 tháng",
    "bảo hành 18 tháng",
    "bảo hành 24 tháng",
    "bảo hành 12 tháng",
    "bh 12 tháng",
    "bh 18 tháng",
    "bh 2 năm",
    "bảo hành",
    "bảo hành",

    # loại sản phẩm chung
    "điện thoại thông minh",
    "điện thoại",
    "smartphone",
    "máy tính bảng",
    "đồng hồ thông minh",
    "vòng đeo tay thông minh",
    "tai nghe bluetooth",
    "tai nghe không dây",
    "tai nghe có dây",
    "củ sạc",
    "sạc nhanh",
    "dây cáp",
    "cáp sạc",
    "phụ kiện",
    "hàng nhập khẩu",

    # mã thị trường / phân phối
    "vn/a", "zp/a", "za/a", "eu", "xsv", "sv"
]

In [6]:
def normalize_unicode(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = unicodedata.normalize("NFC", text)
    return text


def normalize_name_for_matching(text):
    text = normalize_unicode(text)

    # Chuẩn hóa ký hiệu
    text = text.replace("™", "").replace("®", "")
    text = text.replace("gen", " gen ")

    # Chuẩn hóa ký tự phân tách
    text = re.sub(r"[\|\-_/,:;–—]+", " ", text)
    text = re.sub(r"[()\[\]{}]", " ", text)

    # Chuẩn hóa ký hiệu inch
    text = re.sub(r"[”\"']", " inch ", text)

    # Xóa từ nhiễu
    for phrase in sorted(NOISE_PHRASES, key=len, reverse=True):
        pattern = r"\b" + re.escape(phrase) + r"\b"
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE)

    # Chuẩn hóa RAM/ROM thường gặp
    text = re.sub(r"(\d+)\s*\+\s*(\d+)\s*gb", r"\1gb \2gb", text)
    text = re.sub(r"(\d+)\s*/\s*(\d+)\s*gb", r"\1gb \2gb", text)
    text = re.sub(r"(\d+)\s*gb\s*/\s*(\d+)\s*gb", r"\1gb \2gb", text)

    # Chuẩn hóa khoảng trắng
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [7]:
def extract_storage_options(text):
    text = normalize_unicode(text)

    # Chuẩn hóa dạng 8+256GB, 12GB/256GB
    text = re.sub(r"(\d+)\s*\+\s*(\d+)\s*gb", r"\1gb \2gb", text)
    text = re.sub(r"(\d+)\s*/\s*(\d+)\s*gb", r"\1gb \2gb", text)

    matches = re.findall(r"(\d+(?:\.\d+)?)\s*(tb|gb)", text)

    storages = []

    for num, unit in matches:
        val = float(num)

        if unit == "tb":
            if val.is_integer():
                storages.append(f"{int(val)}tb")
            else:
                storages.append(f"{val}tb")

        else:
            # Lọc RAM nhỏ như 4GB, 6GB, 8GB, 12GB, 16GB.
            # Chỉ giữ các giá trị thường là ROM/storage: >= 32GB.
            if val >= 32:
                storages.append(f"{int(val)}gb")

    # Unique nhưng giữ thứ tự xuất hiện
    unique_storages = []
    for s in storages:
        if s not in unique_storages:
            unique_storages.append(s)

    return unique_storages

In [8]:
def extract_product_type(name):
    text = normalize_unicode(name)

    # Đặt phụ kiện lên trước để tránh trường hợp "Cáp sạc Apple Watch" bị gom nhầm vào đồng hồ.
    rules = [
        ("charger_cable_accessory", [
            "cáp", "sạc", "adapter", "keyboard", "pencil", "pen",
            "ốp", "case", "phụ kiện", "power adapter", "usb"
        ]),
        ("phone", [
            "điện thoại", "iphone", "galaxy a", "galaxy s",
            "oppo", "vivo", "tecno spark", "poco", "redmi note"
        ]),
        ("tablet", [
            "máy tính bảng", "ipad", "matepad", "galaxy tab",
            "redmi pad", "xiaomi pad", "poco pad"
        ]),
        ("smartwatch_band", [
            "đồng hồ", "watch", "band", "vòng đeo tay"
        ]),
        ("earphone_speaker", [
            "tai nghe", "buds", "freebuds", "airpods", "sony wf", "sony wh", "jbl", "loa"
        ]),
        ("home_appliance", [
            "máy giặt", "máy hút bụi", "nồi", "máy xay", "quạt", "bear"
        ]),
    ]

    for label, keywords in rules:
        if any(keyword in text for keyword in keywords):
            return label

    return "other"

In [9]:
def first_match(patterns, text):
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            value = match.group(1)
            value = re.sub(r"\s+", " ", value).strip()
            return value
    return None


def clean_base_model(base):
    if not base:
        return ""

    base = normalize_name_for_matching(base)

    # Chuẩn hóa một số trường hợp Apple
    base = base.replace("4th gen", "4")
    base = base.replace("airpods 4th", "airpods 4")

    # Cắt bớt mô tả kỹ thuật bị kéo theo
    base = re.sub(
        r"\b(?:màn|màn hình|pin|camera|thiết kế|màu|inch|wifi|cellular|chống|kháng|thời lượng|nghe gọi|loa kép)\b.*$",
        "",
        base
    )

    base = re.sub(r"\s+", " ", base).strip()
    return base


def extract_base_model(name, brand=None):
    # Dùng cả text gốc và text đã normalize.
    # Một số từ như "cáp sạc" bị xóa trong normalize vì là từ nhiễu,
    # nên phải xử lý phụ kiện trước bằng text gốc.
    raw_text = normalize_unicode(name)
    text = normalize_name_for_matching(name)

    # Accessory patterns first, to avoid grouping cables/chargers as Apple Watch/iPad/etc.
    if ("apple watch" in raw_text) and any(k in raw_text for k in ["cáp", "sạc", "charger", "usb"]):
        return "cáp sạc apple watch usb c"

    if ("apple" in raw_text) and ("20w" in raw_text) and ("adapter" in raw_text or "sạc" in raw_text):
        return "apple 20w usb c power adapter"

    if ("lightning" in raw_text) and ("cáp" in raw_text or "cable" in raw_text):
        return "apple usb c to lightning cable"

    accessory_patterns = [
        r"\b(magic\s*keyboard\s*\d*)\b",
        r"\b(poco\s*smart\s*pen)\b",
        r"\b(poco\s*pad\s*smart\s*keyboard)\b",
        r"\b(sạc\s*xiaomi\s*\d+w\s*hypercharge)\b",
    ]

    acc = first_match(accessory_patterns, text)
    if acc:
        return clean_base_model(acc)

    patterns = [
        # Apple
        r"\b(iphone\s*(?:air|se|\d{1,2})\s*(?:pro max|pro|plus|max)?)\b",
        r"\b(apple\s*iphone\s*(?:air|se|\d{1,2})\s*(?:pro max|pro|plus|max)?)\b",
        r"\b(ipad\s*(?:air|pro|mini|a\d+)?\s*(?:\d{4})?)\b",
        r"\b(apple\s*watch\s*series\s*\d+\s*(?:gps)?\s*(?:\d+mm)?)\b",
        r"\b(apple\s*watch\s*(?:se\s*)?\d*(?:\s*gps)?(?:\s*\d+mm)?)\b",
        r"\b(airpods\s*(?:pro|max)?\s*(?:\d+(?:th)?(?:\s*gen)?)?)\b",

        # Samsung
        r"\b(samsung\s*galaxy\s*(?:s\d+|a\d+|m\d+|z\s*flip\d*|z\s*fold\d*|tab\s*[a-z0-9]+)\s*(?:ultra|plus|fe|lte|5g|4g)?)\b",
        r"\b(galaxy\s*(?:s\d+|a\d+|m\d+|z\s*flip\d*|z\s*fold\d*|tab\s*[a-z0-9]+)\s*(?:ultra|plus|fe|lte|5g|4g)?)\b",

        # Xiaomi / Redmi / POCO
        r"\b(poco\s*pad\s*(?:[a-z0-9]+)?)\b",
        r"\b(poco\s*[a-z]?\d+\s*(?:pro|ultra|lite)?\s*(?:5g)?)\b",
        r"\b(redmi\s*note\s*\d+\s*(?:pro max|pro|plus)?\s*(?:5g)?)\b",
        r"\b(redmi\s*a\d+\s*(?:pro)?\s*(?:5g)?)\b",
        r"\b(redmi\s*pad\s*\d*(?:\s*wi fi)?)\b",
        r"\b(redmi\s*buds\s*\d+\s*(?:play|pro|active)?)\b",
        r"\b(redmi\s*watch\s*\d+\s*(?:active|lite)?)\b",
        r"\b(xiaomi\s*(?:smart\s*band|watch|pad)?\s*\d+\s*(?:active|pro|ultra|lite)?\s*(?:5g)?)\b",
        r"\b(xiaomi\s*\d+\s*(?:pro|ultra|lite)?\s*(?:5g)?)\b",

        # OPPO
        r"\b(oppo\s*(?:reno\s*\d+|a\d+|find\s*[a-z0-9]+|pad|enco\s*[a-z0-9 ]*)\s*(?:pro|plus|flip|5g|4g)?)\b",

        # vivo
        r"\b(vivo\s*(?:v\d+|y\d+)\s*(?:pro|fe|5g|4g)?)\b",

        # TECNO
        r"\b(tecno\s*(?:spark\s*go\s*\d+|spark\s*\d+|pova\s*\d+|camon\s*\d+|buds\s*\d+)\s*(?:pro|go|5g)?)\b",

        # HUAWEI
        r"\b(huawei\s*matepad\s*[a-z0-9. ]{0,20})\b",
        r"\b(huawei\s*watch\s*(?:fit\s*)?\d*(?:\s*series|\s*d2)?)\b",
        r"\b(huawei\s*freebuds\s*[a-z0-9 ]{0,15})\b",
        r"\b(huawei\s*band\s*\d+)\b",
        r"\b(huawei\s*(?:freeclip|freearc))\b",

        # realme
        r"\b(realme\s*(?:watch|c|note|buds)?\s*[a-z0-9 ]{0,15})\b",

        # Audio / accessories / home appliances
        r"\b(sony\s*(?:wf|wh)[a-z0-9\-]+)\b",
        r"\b(jbl\s*[a-z0-9 ]{0,20})\b",
        r"\b(belkin\s*[a-z0-9 ]{0,20})\b",
        r"\b(bear\s*[a-z0-9\- ]{0,25})\b",
    ]

    base = first_match(patterns, text)

    if base:
        return clean_base_model(base)

    # Fallback nếu không bắt được model rõ ràng
    tokens = re.findall(r"[a-z0-9à-ỹ]+", text)

    if brand is not None and not pd.isna(brand):
        brand_clean = normalize_unicode(brand)
        if brand_clean and brand_clean not in tokens:
            tokens = [brand_clean] + tokens

    return " ".join(tokens[:6]) if tokens else text

In [10]:
def build_canonical_name(row):
    name = row.get("product_name", "")
    brand = row.get("brand", "")

    base = extract_base_model(name, brand)
    storage_options = extract_storage_options(name)

    product_type = row.get("product_type", "")

    # Chỉ thêm dung lượng cho phone/tablet. Phụ kiện như cáp/sạc không cần thêm storage.
    if product_type in ["phone", "tablet"] and len(storage_options) == 1:
        canonical = f"{base} {storage_options[0]}"
    else:
        canonical = base

    canonical = normalize_name_for_matching(canonical)
    canonical = re.sub(r"\s+", " ", canonical).strip()

    return canonical


products["product_type"] = products["product_name"].apply(extract_product_type)
products["product_name_norm"] = products["product_name"].apply(normalize_name_for_matching)
products["storage_options"] = products["product_name"].apply(lambda x: ", ".join(extract_storage_options(x)))
products["canonical_product_name"] = products.apply(build_canonical_name, axis=1)

# Tạo ID nhóm sản phẩm
products["canonical_product_id"] = products["canonical_product_name"].astype("category").cat.codes

display(products[
    [
        "shop_clean", "brand", "product_type",
        "product_name", "product_name_norm",
        "storage_options", "canonical_product_name", "canonical_product_id"
    ]
].head(30))

,shop_clean,brand,product_type,product_name,product_name_norm,storage_options,canonical_product_name,canonical_product_id
0,xiaomiofficialstore,Xiaomi,smartwatch_band,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169
1,xiaomiofficialstore,Xiaomi,smartwatch_band,"Đồng hồ thông minh Redmi Watch 5 Lite | Màn hình AMOLED 2"" l Nghe gọi Bluetooth | +150 chế độ thể thao | 5ATM | GPS/...",redmi watch 5 lite màn hình amoled 2 inch l nghe gọi bluetooth +150 chế độ thể thao 5atm gps gnss,,redmi watch 5 lite,170
2,xiaomiofficialstore,Xiaomi,phone,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",poco x8 pro 5g 8gb 256gb 8gb 512gb 12gb 512gb màn 6.59 inch 1 5k 120hz d8500u 50mp,"256gb, 512gb",poco x8 pro 5g,153
3,xiaomiofficialstore,Xiaomi,charger_cable_accessory,Sạc Xiaomi 67W HyperCharge Combo (Type-A) EU,sạc xiaomi 67w hypercharge type a,,sạc xiaomi 67w hypercharge,203
4,xiaomiofficialstore,Poco,phone,"[Livestream] Điện thoại POCO X7 Pro 5G (8+256GB | 12+256GB) | Màn 6.67"" 120Hz AMOLED | D8400-Ultra",poco x7 pro 5g 8gb 256gb 12gb 256gb màn 6.67 inch 120hz amoled d8400 ultra,256gb,poco x7 pro 5g 256gb,152
5,xiaomiofficialstore,Xiaomi,phone,"Điện thoại POCO M8 5G (8+256GB | 8+512GB) | Màn Flow AMOLED 6.77"" 120Hz | Snapdragon 6Gen3 | Camera 50MP",poco m8 5g 8gb 256gb 8gb 512gb màn flow amoled 6.77 inch 120hz snapdragon 6 gen 3 camera 50mp,"256gb, 512gb",poco m8 5g,149
6,xiaomiofficialstore,Xiaomi,smartwatch_band,Vòng đeo tay thông minh Xiaomi Smart Band 9 Active | Màn hình 1.47'' TFT 60Hz | Pin 18 ngày | Theo dõi sức khỏe cả ngày,xiaomi smart band 9 active màn hình 1.47 inch inch tft 60hz pin 18 ngày theo dõi sức khỏe cả ngày,,xiaomi smart band 9 active,248
7,xiaomiofficialstore,Xiaomi,smartwatch_band,Vòng đeo tay thông minh Xiaomi Smart Band 9 Pro | Màn hình AMOLED 1.74'' | Thời lượng pin 21 ngày | GNSS/GPS/5ATM/BT5.4,xiaomi smart band 9 pro màn hình amoled 1.74 inch inch thời lượng pin 21 ngày gnss gps 5atm bt5.4,,xiaomi smart band 9 pro,249
8,xiaomiofficialstore,Poco,phone,"Điện thoại POCO X7 Pro 5G (12+256GB) | Màn 6.67"" 120Hz AMOLED | 8400-Ultra | Camera 50MP | 6000mAh",poco x7 pro 5g 12gb 256gb màn 6.67 inch 120hz amoled 8400 ultra camera 50mp 6000mah,256gb,poco x7 pro 5g 256gb,152
9,xiaomiofficialstore,Xiaomi,phone,Điện thoại Redmi Note 15 (6+128GB) | Pin lớn 6000mAh | Màn hình siêu bền | MT Helio G100-Ultra,redmi note 15 6gb 128gb pin lớn 6000mah màn hình siêu bền mt helio g100 ultra,128gb,redmi note 15 128gb,164
10,xiaomiofficialstore,Xiaomi,phone,"[Livestream] Điện thoại POCO M8 5G (8+256GB | 8+512GB) | Màn Flow AMOLED 6.77"" 120Hz | Snapdragon 6Gen3",poco m8 5g 8gb 256gb 8gb 512gb màn flow amoled 6.77 inch 120hz snapdragon 6 gen 3,"256gb, 512gb",poco m8 5g,149
11,xiaomiofficialstore,Xiaomi,phone,"[Livestream] (Pre-Order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K | D8500U",poco x8 pro 5g 8gb 256gb 8gb 512gb 12gb 512gb màn 6.59 inch 1 5k d8500u,"256gb, 512gb",poco x8 pro 5g,153
12,xiaomiofficialstore,Xiaomi,smartwatch_band,"Đồng hồ thông minh Xiaomi Watch 2 | Màn hình AMOLED 1.43"" | 12 Kênh theo dõi sức khỏe | HĐH WearOS | Wifi/BT/GPS/NFC",xiaomi watch 2 màn hình amoled 1.43 inch 12 kênh theo dõi sức khỏe hđh wearos wifi bt gps nfc,,xiaomi watch 2,251
13,xiaomiofficialstore,Xiaomi,charger_cable_accessory,[HÀNG TẶNG] POCO Smart Pen (For POCO PAD only),poco smart pen for poco pad only,,poco smart pen,151
14,xiaomiofficialstore,Xiaomi,phone,[Livestream] Điện thoại Xiaomi 15 (12+256GB |12+512GB) | 3 Camera Leica | Snapdragon 8 Elite,xiaomi 15 12gb 256gb 12gb 512gb 3 camera leica snapdragon 8 elite,"256gb, 512gb",xiaomi 15,241
15,xiaomiofficialstore,Xiaomi,charger_cable_accessory,[HÀNG TẶNG KHÔNG BÁN] POCO PAD Smart Keyboard (For POCO PAD only),poco pad smart keyboard for poco pad only,,poco pad smart keyboard,150
16,xiaomiofficialstore,Xiaomi,phone,"[Livestream] Điện thoại Redmi Note 15 5G (6+128GB) | Màn hình 6,77"" FHD+ | Snapdragon® 6 Gen 3 | Camera nét 108MP",redmi note 15 5g 6gb 128gb màn hình 6 77 inch fhd+ snapdragon 6 gen 3 camera nét 108mp,128gb,redmi note 15 5g 128gb,165
17,xiaomiofficialstore,Xiaomi,phone,"Điện thoại Redmi A7 Pro (4+128 GB) | Pin lớn 6000mAh | Màn hình sống động 6.9"" | Vi xử lý 8 nhân",redmi a7 pro 4gb 128gb pin lớn 6000mah màn hình sống động 6.9 inch vi xử lý 8 nhân,128gb,redmi a7 pro 128gb,162
18,xiaomiofficialstore,Xiaomi,earphone_speaker,[QUÀ TẶNG màu ngẫu nhiên] Tai nghe Bluetooth Redmi Buds 6 Play | Thời Lượng Nghe 36H,redmi buds 6 play thời lượng nghe 36h,,redmi buds 6 play,163
19,xiaomiofficialstore,Xiaomi,phone,[Livestream] Điện thoại Redmi Note 15 (6+128GB) | Pin lớn 6000mAh | Màn hình siêu bền | MT Helio G100-Ultra,redmi note 15 6gb 128gb pin lớn 6000mah màn hình siêu bền mt helio g100 ultra,128gb,redmi note 15 128gb,164
20,xiaomiofficialstore,Xiaomi,smartwatch_band,Hàng Chính Hãng Phân Phối Bởi Digiworld | Đồng Hồ Thông Minh Xiaomi Mi Watch Lite,phân phối bởi digiworld xiaomi mi watch lite,,phân phối bởi digiworld xiaomi mi,146
21,xiaomiofficialstore,Xiaomi,other,"Camera Thông Minh Xiaomi Outdoor Camera AW200 / BW500 / CW500 Dual EU | 2,5K | Nhìn đêm 1080p | Chịu thời tiết nắng mưa",camera thông minh xiaomi outdoor camera aw200 bw500 cw500 dual 2 5k nhìn đêm 1080p chịu thời tiết nắng mưa,,camera thông minh xiaomi outdoor camera,40
22,xiaomiofficialstore,Xiaomi,tablet,"Máy tính bảng Redmi Pad (3+64GB) | Màn hình LCD IPS 10.61"" 90Hz 2K | MediaTek Helio G99 | Pin 8000mAh",redmi pad 3gb 64gb màn hình lcd ips 10.61 inch 90hz 2k mediatek helio g99 pin 8000mah,64gb,redmi pad 64gb,168
23,xiaomiofficialstore,Poco,phone,"[VOUCHER 200K] [Livestream] Điện thoại POCO F8 Pro 12+512GB | Màn POCO HyperRGB AMOLED 6.59"" 120Hz | Snapdragon 8 Elite",poco f8 pro 12gb 512gb màn poco hyperrgb amoled 6.59 inch 120hz snapdragon 8 elite,512gb,poco f8 pro 512gb,148
24,xiaomiofficialstore,Poco,phone,"[VOUCHER 200K] Điện thoại POCO F8 Pro (12+256GB | 12+512GB) | Màn POCO HyperRGB AMOLED 6.59"" 120Hz | Snapdragon 8 Elite",poco f8 pro 12gb 256gb 12gb 512gb màn poco hyperrgb amoled 6.59 inch 120hz snapdragon 8 elite,"256gb, 512gb",poco f8 pro,147
25,xiaomiofficialstore,Xiaomi,earphone_speaker,Loa Bluetooth Xiaomi Sound Party NS7-GL 50W,loa bluetooth xiaomi sound party ns7 gl 50w,,loa bluetooth xiaomi sound party ns7,101
26,xiaomiofficialstore,Xiaomi,phone,"Điện thoại Xiaomi 15 (12+512GB) | Màn 6.3"" AMOLED | 3 Camera Leica | Snapdragon 8 Elite HyperAI",xiaomi 15 12gb 512gb màn 6.3 inch amoled 3 camera leica snapdragon 8 elite hyperai,512gb,xiaomi 15 512gb,242
27,xiaomiofficialstore,Xiaomi,other,Lõi lọc không khí thông minh Xiaomi Smart Air Purifier Elite,lõi lọc không khí thông minh xiaomi smart air purifier elite,,lõi lọc không khí thông minh,107
28,xiaomiofficialstore,Xiaomi,charger_cable_accessory,[Livestream] Xiaomi Power Bank 10000mAh Integrated Cable Màu Xanh Gọn nhẹ Có Sẵn Cáp,xiaomi power bank 10000mah integrated cable màu xanh gọn nhẹ có sẵn cáp,,xiaomi power bank 10000mah integrated cable,245
29,xiaomiofficialstore,Xiaomi,phone,"Điện thoại Redmi Note 15 5G (6+128GB) | Màn hình 6,77"" FHD+ | Snapdragon® 6 Gen 3 | Camera nét 108MP | Chống va đập ...",redmi note 15 5g 6gb 128gb màn hình 6 77 inch fhd+ snapdragon 6 gen 3 camera nét 108mp chống va đập 1.7m,128gb,redmi note 15 5g 128gb,165

In [11]:
canonical_group_summary = (
    products
    .groupby(["canonical_product_id", "canonical_product_name"])
    .agg(
        num_items=("item_id", "nunique"),
        num_shops=("shop_clean", "nunique"),
        product_type=("product_type", lambda x: x.mode().iloc[0] if len(x.mode()) else "unknown"),
        min_price=("current_price", "min"),
        max_price=("current_price", "max"),
        avg_rating=("rating", "mean"),
        total_sold=("sold_count_num", "sum"),
        example_names=("product_name", lambda x: " || ".join(x.head(5)))
    )
    .reset_index()
    .sort_values(["num_shops", "num_items", "total_sold"], ascending=False)
)

display(canonical_group_summary.head(30))

,canonical_product_id,canonical_product_name,num_items,num_shops,product_type,min_price,max_price,avg_rating,total_sold,example_names
5,5,apple 20w usb c power adapter,4,2,charger_cable_accessory,429000.0,1098000.0,4.941983,67311,Sạc Apple 20W USB-C Power Adapter || Phụ kiện Apple 20W USB-C Power Adapter chính hãng ZA/A || COMBO Củ sạc Apple 20...
2,2,airpods 4,3,2,earphone_speaker,3590000.0,5690000.0,4.920067,28000,Apple AirPods 4th gen || Tai nghe Bluetooth AirPods 4 Chính hãng || Tai nghe AirPods 4 Khử ồn chủ động Chính hãng
72,72,ipad a16 128gb,3,2,tablet,9800000.0,14690000.0,4.953416,20299,Apple iPad A16 11 inch 2025 Wifi 128GB || Apple iPad A16 11 inch 2025 Wifi + Cellular 128GB || iPad A16 11 inch WIFI...
181,181,samsung galaxy a36 5g 128gb,3,2,phone,7690000.0,8975000.0,4.940075,4005,"Điện thoại Samsung Galaxy A36 5G (8/128GB), Màn Hình FHD 6.7”, Mặt lưng kính, AI-Create Filter, Chip Snapdragon 6 Ge..."
74,74,ipad air 128gb,3,2,tablet,16689000.0,20990000.0,4.988095,306,"Máy tính bảng iPad Air, M4 chip, 11 inch, 128GB || iPad Air M4 11 inch WIFI 5G 128GB Chính hãng ZA/A || iPad Air M4 ..."
192,192,samsung galaxy tab a11 64gb,3,2,tablet,3480000.0,4530000.0,3.333333,138,Samsung Galaxy Tab A11 Wifi 4GB/64GB - Hàng Chính Hãng || Máy tính bảng Samsung Galaxy Tab A11 Wifi 4GB | 64GB - Màn...
82,82,iphone 15 128gb,2,2,phone,18490000.0,18490000.0,4.934268,30000,Điện thoại Apple iPhone 15 128GB || Apple iPhone 15 128GB Chính hãng VN/A
91,91,iphone 17 pro max 256gb,2,2,phone,37990000.0,38890000.0,4.963077,20000,Điện thoại Apple iPhone 17 Pro Max 256GB || Apple iPhone 17 Pro Max 256GB Chính hãng ZP/A
84,84,iphone 16 128gb,2,2,phone,20790000.0,22290000.0,4.939649,11000,Điện thoại Apple iPhone 16 128GB || Apple iPhone 16 128GB Chính hãng VN/A
10,10,apple usb c to lightning cable,2,2,charger_cable_accessory,389000.0,549000.0,4.973940,10340,Phụ kiện Apple USB-C TO LIGHTNING CABLE (1 M) Chính hãng (dùng cho iPhone 14 series trở xuống) || Cáp sạc nhanh Belk...
87,87,iphone 17 256gb,2,2,phone,24999000.0,25890000.0,4.951192,7000,Điện thoại Apple iPhone 17 256GB || Apple iPhone 17 256GB Chính hãng ZP/A
92,92,iphone 17 pro max 512gb,2,2,phone,44499000.0,45490000.0,4.963991,7000,Điện thoại Apple iPhone 17 Pro Max 512GB || Apple iPhone 17 Pro Max 512GB Chính hãng ZP/A
88,88,iphone 17 pro 256gb,2,2,phone,35390000.0,35890000.0,4.958241,5898,Điện thoại Apple iPhone 17 Pro 256GB || Apple iPhone 17 Pro 256GB Chính hãng ZP/A
85,85,iphone 16 plus 128gb,2,2,phone,24990000.0,26090000.0,4.944779,5867,Điện thoại Apple iPhone 16 Plus 128GB || Apple iPhone 16 Plus 128GB Chính hãng VN/A
83,83,iphone 15 256gb,2,2,phone,21489000.0,23090000.0,4.943305,4000,Điện thoại Apple iPhone 15 256GB || Apple iPhone 15 256GB Chính hãng VN/A
76,76,ipad mini 128gb,2,2,tablet,13690000.0,14290000.0,4.947171,3000,Apple iPad mini 7 8.3-inch Wi-Fi 128GB || iPad Mini 7 WIFI 128GB Chính hãng
93,93,iphone air 256gb,2,2,phone,24290000.0,24590000.0,4.899224,2970,Điện thoại Apple iPhone Air 256GB || Apple iPhone Air 256GB Chính hãng ZP/A
179,179,samsung galaxy a26 5g 128gb,2,2,phone,6275000.0,6790000.0,4.949119,2021,"Điện Thoại Samsung Galaxy A26 5G 8GB/128GB || Điện thoại Samsung Galaxy A26 5G 8GB | 128GB - Màn hình 6,7"" 120Hz, Ex..."
178,178,samsung galaxy a17 lte 128gb,2,2,phone,4775000.0,5930000.0,4.915323,1162,"Điện Thoại Samsung Galaxy A17 LTE 8GB/128GB || Điện thoại Samsung Galaxy A17 LTE 8GB | 128GB - Màn hình 6,7"" 90Hz, 5..."
226,226,tủ lạnh samsung ngăn đông trên,5,1,other,5744000.0,10657000.0,4.364324,2499,"Tủ Lạnh Samsung Ngăn Đông Trên 305L RT31CG5424B1SV - Ngăn Đông Mềm 4 Chế Độ Optimal Fresh+, màu Đen || Tủ Lạnh Samsu..."
68,68,huawei watch,4,1,smartwatch_band,4710000.0,4710000.0,4.953095,12299,Đồng Hồ Thông Minh HUAWEI WATCH GT6 Series | Tập Luyện Nâng Cao | Theo Dõi Sức Khỏe Toàn Diện | Pin Đến 21 Ngày || [...
54,54,huawei band 11,4,1,smartwatch_band,950000.0,1670000.0,4.863347,6042,"Vòng Đeo Tay Thông Minh HUAWEI Band 11 Series | Mỏng Nhẹ, Màn Hình Lớn| Quản Lý Sức Khỏe Nâng Cao| 100+ Chế Độ Luyện..."
122,122,máy tính xách tay apple macbook,4,1,other,16499000.0,35499000.0,4.928571,311,"Máy tính xách tay Apple MacBook Air 13.6 inch, M5, 10-core CPU, 8-core GPU, 512GB || Máy Tính Xách Tay Apple MacBook..."
209,209,tecno buds 4,4,1,earphone_speaker,440000.0,990000.0,2.428571,58,[Ưu Đãi LS] Tai Nghe Bluetooth 5.4 TECNO BUDS 4 AIR Chống Ồn AI-ENC | Kháng Nước IPX4 | Nhỏ Gọn || [Ưu Đãi LS] Tai N...
119,119,máy hút bụi dạng hộp samsung,3,1,home_appliance,1546720.0,2486400.0,4.894581,18000,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh || Máy hút bụi dạng hộp Samsung ..."
216,216,tecno spark 40 pro,3,1,charger_cable_accessory,4990000.0,6290000.0,3.265451,3418,Điện thoại TECNO SPARK 40 PRO (8+8)GB/128GB - Màn hình AMOLED 1.5K & 144Hz | Mỏng 6.69mm | 5200mAh sạc 45W || Điện t...
212,212,tecno pova 7,3,1,charger_cable_accessory,4590000.0,5290000.0,4.923524,1411,"Điện thoại Tecno Pova 7 8/128GB | Siêu Pin 7000mAh | Sạc Nhanh 45W | Màn Hình 6.78"" FHD+ 120Hz | Chính hãng || [Ưu Đ..."
71,71,ipad,3,1,charger_cable_accessory,289000.0,949000.0,3.268185,1128,Bút cảm ứng cho iPad ESR Digital Pencil GEO 6C006 phiên bản 2025 || [KOL] Bút cảm ứng cho iPad ESR Digital Pencil GE...
70,70,huawei watch fit 4 series,2,1,smartwatch_band,2670000.0,2670000.0,4.906951,15000,Đồng Hồ Thông Minh HUAWEI WATCH FIT 4 Series | Mỏng Nhẹ | Thể Thao & Sức Khỏe | Lên Đến 10 Ngày Sử Dụng| ECG* || [LI...
152,152,poco x7 pro 5g 256gb,2,1,phone,10690000.0,10690000.0,4.941434,9000,"[Livestream] Điện thoại POCO X7 Pro 5G (8+256GB | 12+256GB) | Màn 6.67"" 120Hz AMOLED | D8400-Ultra || Điện thoại POC..."

In [12]:
same_product_candidates = canonical_group_summary[
    canonical_group_summary["num_shops"] >= 2
].copy()

print("Số nhóm sản phẩm có từ 2 shop trở lên:", same_product_candidates.shape[0])
display(same_product_candidates.head(30))

Số nhóm sản phẩm có từ 2 shop trở lên: 19

,canonical_product_id,canonical_product_name,num_items,num_shops,product_type,min_price,max_price,avg_rating,total_sold,example_names
5,5,apple 20w usb c power adapter,4,2,charger_cable_accessory,429000.0,1098000.0,4.941983,67311,Sạc Apple 20W USB-C Power Adapter || Phụ kiện Apple 20W USB-C Power Adapter chính hãng ZA/A || COMBO Củ sạc Apple 20...
2,2,airpods 4,3,2,earphone_speaker,3590000.0,5690000.0,4.920067,28000,Apple AirPods 4th gen || Tai nghe Bluetooth AirPods 4 Chính hãng || Tai nghe AirPods 4 Khử ồn chủ động Chính hãng
72,72,ipad a16 128gb,3,2,tablet,9800000.0,14690000.0,4.953416,20299,Apple iPad A16 11 inch 2025 Wifi 128GB || Apple iPad A16 11 inch 2025 Wifi + Cellular 128GB || iPad A16 11 inch WIFI...
181,181,samsung galaxy a36 5g 128gb,3,2,phone,7690000.0,8975000.0,4.940075,4005,"Điện thoại Samsung Galaxy A36 5G (8/128GB), Màn Hình FHD 6.7”, Mặt lưng kính, AI-Create Filter, Chip Snapdragon 6 Ge..."
74,74,ipad air 128gb,3,2,tablet,16689000.0,20990000.0,4.988095,306,"Máy tính bảng iPad Air, M4 chip, 11 inch, 128GB || iPad Air M4 11 inch WIFI 5G 128GB Chính hãng ZA/A || iPad Air M4 ..."
192,192,samsung galaxy tab a11 64gb,3,2,tablet,3480000.0,4530000.0,3.333333,138,Samsung Galaxy Tab A11 Wifi 4GB/64GB - Hàng Chính Hãng || Máy tính bảng Samsung Galaxy Tab A11 Wifi 4GB | 64GB - Màn...
82,82,iphone 15 128gb,2,2,phone,18490000.0,18490000.0,4.934268,30000,Điện thoại Apple iPhone 15 128GB || Apple iPhone 15 128GB Chính hãng VN/A
91,91,iphone 17 pro max 256gb,2,2,phone,37990000.0,38890000.0,4.963077,20000,Điện thoại Apple iPhone 17 Pro Max 256GB || Apple iPhone 17 Pro Max 256GB Chính hãng ZP/A
84,84,iphone 16 128gb,2,2,phone,20790000.0,22290000.0,4.939649,11000,Điện thoại Apple iPhone 16 128GB || Apple iPhone 16 128GB Chính hãng VN/A
10,10,apple usb c to lightning cable,2,2,charger_cable_accessory,389000.0,549000.0,4.973940,10340,Phụ kiện Apple USB-C TO LIGHTNING CABLE (1 M) Chính hãng (dùng cho iPhone 14 series trở xuống) || Cáp sạc nhanh Belk...
87,87,iphone 17 256gb,2,2,phone,24999000.0,25890000.0,4.951192,7000,Điện thoại Apple iPhone 17 256GB || Apple iPhone 17 256GB Chính hãng ZP/A
92,92,iphone 17 pro max 512gb,2,2,phone,44499000.0,45490000.0,4.963991,7000,Điện thoại Apple iPhone 17 Pro Max 512GB || Apple iPhone 17 Pro Max 512GB Chính hãng ZP/A
88,88,iphone 17 pro 256gb,2,2,phone,35390000.0,35890000.0,4.958241,5898,Điện thoại Apple iPhone 17 Pro 256GB || Apple iPhone 17 Pro 256GB Chính hãng ZP/A
85,85,iphone 16 plus 128gb,2,2,phone,24990000.0,26090000.0,4.944779,5867,Điện thoại Apple iPhone 16 Plus 128GB || Apple iPhone 16 Plus 128GB Chính hãng VN/A
83,83,iphone 15 256gb,2,2,phone,21489000.0,23090000.0,4.943305,4000,Điện thoại Apple iPhone 15 256GB || Apple iPhone 15 256GB Chính hãng VN/A
76,76,ipad mini 128gb,2,2,tablet,13690000.0,14290000.0,4.947171,3000,Apple iPad mini 7 8.3-inch Wi-Fi 128GB || iPad Mini 7 WIFI 128GB Chính hãng
93,93,iphone air 256gb,2,2,phone,24290000.0,24590000.0,4.899224,2970,Điện thoại Apple iPhone Air 256GB || Apple iPhone Air 256GB Chính hãng ZP/A
179,179,samsung galaxy a26 5g 128gb,2,2,phone,6275000.0,6790000.0,4.949119,2021,"Điện Thoại Samsung Galaxy A26 5G 8GB/128GB || Điện thoại Samsung Galaxy A26 5G 8GB | 128GB - Màn hình 6,7"" 120Hz, Ex..."
178,178,samsung galaxy a17 lte 128gb,2,2,phone,4775000.0,5930000.0,4.915323,1162,"Điện Thoại Samsung Galaxy A17 LTE 8GB/128GB || Điện thoại Samsung Galaxy A17 LTE 8GB | 128GB - Màn hình 6,7"" 90Hz, 5..."

In [13]:
product_identity = products[
    [
        "shop_id", "item_id", "shop_clean",
        "brand", "product_type",
        "product_name_norm",
        "storage_options",
        "canonical_product_name",
        "canonical_product_id"
    ]
].drop_duplicates(["shop_id", "item_id"])

reviews_processed = reviews.merge(
    product_identity,
    on=["shop_id", "item_id", "shop_clean"],
    how="left"
)

print("Reviews before merge:", reviews.shape)
print("Reviews after merge:", reviews_processed.shape)
print("Missing canonical_product_id:", reviews_processed["canonical_product_id"].isna().sum())

display(reviews_processed.head())

Reviews before merge: (8992, 15)
Reviews after merge: (8992, 21)
Missing canonical_product_id: 1

,shop,shop_id,item_id,product_name,product_url,review_text,review_star,author_username,ctime,model_name,liked_count,review_text_clean,sentiment_by_star,review_star_group,shop_clean,brand,product_type,product_name_norm,storage_options,canonical_product_name,canonical_product_id
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Giao hàngg nhanh, dùngg khá ổn shop có tư vấn. Mua được giá rẻe.",5,doyen9,1768667109,Đen,NaN,"giao hàngg nhanh, dùngg khá ổn shop có tư vấn. mua được giá rẻe.",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169.0
1,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:Redmi Active 5\nChất lượng sản phẩm:Mình đánh giá sau\n\nRedmi Active 5.\nDo hết hàng nên mình đợi kh...,5,dthang92,1765961178,Bạc,NaN,đúng với mô tả:redmi active 5 chất lượng sản phẩm:mình đánh giá sau redmi active 5. do hết hàng nên mình đợi khá lâu...,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169.0
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",5,p*****f,1767692199,Đen,NaN,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169.0
3,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:ok\nChất lượng sản phẩm:ok\n\nsp khá ổn trong tầm giá,5,b*****0,1764553050,Bạc,NaN,đúng với mô tả:ok chất lượng sản phẩm:ok sp khá ổn trong tầm giá,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169.0
4,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Giao hàng nhanh chóng. Hình ảnh và video mang tính chất nhận xu.,5,d*****7,1769928670,Đen,NaN,giao hàng nhanh chóng. hình ảnh và video mang tính chất nhận xu.,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,,redmi watch 5 active,169.0

In [14]:
review_coverage = (
    reviews_processed
    .groupby(["shop_id", "item_id", "canonical_product_id", "canonical_product_name"])
    .agg(
        review_count=("review_text_clean", "count"),
        avg_review_star=("review_star", "mean")
    )
    .reset_index()
    .sort_values("review_count", ascending=False)
)

display(review_coverage.head(30))

,shop_id,item_id,canonical_product_id,canonical_product_name,review_count,avg_review_star
4,65589552,26728758506,173.0,samsung galaxy a06 5g 128gb,304,4.884868
52,308461157,17455633222,10.0,apple usb c to lightning cable,304,4.993421
20,88201679,25171387783,5.0,apple 20w usb c power adapter,300,5.000000
0,65589552,1622955655,119.0,máy hút bụi dạng hộp samsung,299,4.973244
53,308461157,18391063878,80.0,iphone 14,298,4.996644
62,308461157,27415713043,2.0,airpods 4,296,4.945946
25,88201679,27110898667,84.0,iphone 16 128gb,293,4.914676
78,340431675,24740059865,152.0,poco x7 pro 5g 256gb,292,4.914384
26,88201679,28032850215,72.0,ipad a16 128gb,292,4.965753
15,88201679,10753341705,79.0,iphone 13 128gb,291,4.989691
21,88201679,26210898087,2.0,airpods 4,291,4.986254
50,308461157,13928850471,78.0,iphone 13,291,4.931271
24,88201679,27041370670,91.0,iphone 17 pro max 256gb,287,4.909408
16,88201679,18093055535,82.0,iphone 15 128gb,283,4.989399
70,308461157,42568221380,91.0,iphone 17 pro max 256gb,276,4.898551
34,88201679,42068693165,3.0,airpods pro 3,268,4.869403
7,65589552,29928135317,181.0,samsung galaxy a36 5g 128gb,262,4.774809
56,308461157,23483695459,81.0,iphone 15,245,4.959184
48,93963889,41318341242,68.0,huawei watch,243,4.950617
47,93963889,40473928663,62.0,huawei matepad 11.5 papermatte 8gb,239,4.485356
102,442733715,29980129689,214.0,tecno spark 30 5g 128gb,232,4.836207
49,308461157,4953760805,5.0,apple 20w usb c power adapter,227,4.995595
69,308461157,42168225876,92.0,iphone 17 pro max 512gb,192,4.906250
17,88201679,22880091028,83.0,iphone 15 256gb,191,4.895288
55,308461157,22654646317,83.0,iphone 15 256gb,169,4.946746
5,65589552,29703218643,102.0,lò vi sóng samsung 20l ms20a3010al,164,4.768293
54,308461157,21684104015,82.0,iphone 15 128gb,156,4.987179
22,88201679,26768295651,76.0,ipad mini 128gb,144,4.826389
63,308461157,27665729077,2.0,airpods 4,140,4.842857
18,88201679,24246902031,92.0,iphone 17 pro max 512gb,124,4.838710

In [15]:
OUTPUT_DIR = "/kaggle/working"

if not os.path.exists(OUTPUT_DIR):
    OUTPUT_DIR = "."

products_output = os.path.join(OUTPUT_DIR, "shopee_products_processed.csv")
reviews_output = os.path.join(OUTPUT_DIR, "shopee_reviews_processed.csv")
group_output = os.path.join(OUTPUT_DIR, "canonical_group_summary.csv")
same_product_output = os.path.join(OUTPUT_DIR, "same_product_candidates.csv")

products.to_csv(products_output, index=False, encoding="utf-8-sig")
reviews_processed.to_csv(reviews_output, index=False, encoding="utf-8-sig")
canonical_group_summary.to_csv(group_output, index=False, encoding="utf-8-sig")
same_product_candidates.to_csv(same_product_output, index=False, encoding="utf-8-sig")

print("Saved files:")
print(products_output)
print(reviews_output)
print(group_output)
print(same_product_output)

Saved files:
/kaggle/working/shopee_products_processed.csv
/kaggle/working/shopee_reviews_processed.csv
/kaggle/working/canonical_group_summary.csv
/kaggle/working/same_product_candidates.csv

In [16]:
import os
import pandas as pd
import numpy as np
import torch
from transformers import pipeline
from tqdm.auto import tqdm

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

In [17]:
PRODUCTS_PATH = "/kaggle/working/shopee_products_processed.csv"
REVIEWS_PATH = "/kaggle/working/shopee_reviews_processed.csv"

products = pd.read_csv(PRODUCTS_PATH)
reviews = pd.read_csv(REVIEWS_PATH)

print("Products:", products.shape)
print("Reviews:", reviews.shape)

display(products.head())
display(reviews.head())

Products: (347, 23)
Reviews: (8992, 21)

,shop,shop_id,item_id,product_name,current_price,original_price,discount_percent,rating,rating_count,sold_count,monthly_sold,liked_count,brand,product_url,product_name_clean,sold_count_num,monthly_sold_num,shop_clean,product_type,product_name_norm,storage_options,canonical_product_name,canonical_product_id
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",880000.0,880000.0,0,5.000000,NaN,889 đã bán,808 đã bán/tháng,59,Xiaomi,https://shopee.vn/product/340431675/28914299334,đồng hồ thông minh redmi watch 5 active màn hình lcd 2 l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,889,808,xiaomiofficialstore,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169
1,xiaomiofficialstore,340431675,27514293609,"Đồng hồ thông minh Redmi Watch 5 Lite | Màn hình AMOLED 2"" l Nghe gọi Bluetooth | +150 chế độ thể thao | 5ATM | GPS/...",1390000.0,1390000.0,0,3.833333,NaN,31 đã bán,1 đã bán/tháng,35,Xiaomi,https://shopee.vn/product/340431675/27514293609,đồng hồ thông minh redmi watch 5 lite màn hình amoled 2 l nghe gọi bluetooth +150 chế độ thể thao 5atm gps/gnss,31,1,xiaomiofficialstore,smartwatch_band,redmi watch 5 lite màn hình amoled 2 inch l nghe gọi bluetooth +150 chế độ thể thao 5atm gps gnss,NaN,redmi watch 5 lite,170
2,xiaomiofficialstore,340431675,48656445603,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",9490000.0,10990000.0,14,4.956757,NaN,533 đã bán,191 đã bán/tháng,511,Xiaomi,https://shopee.vn/product/340431675/48656445603,"pre-order điện thoại poco x8 pro 5g 8+256gb 8+512gb 12+512gb màn 6.59 1,5k 120hz d8500u 50mp",533,191,xiaomiofficialstore,phone,poco x8 pro 5g 8gb 256gb 8gb 512gb 12gb 512gb màn 6.59 inch 1 5k 120hz d8500u 50mp,"256gb, 512gb",poco x8 pro 5g,153
3,xiaomiofficialstore,340431675,26262566585,Sạc Xiaomi 67W HyperCharge Combo (Type-A) EU,890000.0,890000.0,0,4.924051,NaN,366 đã bán,181 đã bán/tháng,78,Xiaomi,https://shopee.vn/product/340431675/26262566585,sạc xiaomi 67w hypercharge combo type-a eu,366,181,xiaomiofficialstore,charger_cable_accessory,sạc xiaomi 67w hypercharge type a,NaN,sạc xiaomi 67w hypercharge,203
4,xiaomiofficialstore,340431675,26221234933,"[Livestream] Điện thoại POCO X7 Pro 5G (8+256GB | 12+256GB) | Màn 6.67"" 120Hz AMOLED | D8400-Ultra",10690000.0,10690000.0,0,4.941467,NaN,5k+ đã bán,1k+ đã bán/tháng,1760,Poco,https://shopee.vn/product/340431675/26221234933,livestream điện thoại poco x7 pro 5g 8+256gb 12+256gb màn 6.67 120hz amoled d8400-ultra,5000,1000,xiaomiofficialstore,phone,poco x7 pro 5g 8gb 256gb 12gb 256gb màn 6.67 inch 120hz amoled d8400 ultra,256gb,poco x7 pro 5g 256gb,152

,shop,shop_id,item_id,product_name,product_url,review_text,review_star,author_username,ctime,model_name,liked_count,review_text_clean,sentiment_by_star,review_star_group,shop_clean,brand,product_type,product_name_norm,storage_options,canonical_product_name,canonical_product_id
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Giao hàngg nhanh, dùngg khá ổn shop có tư vấn. Mua được giá rẻe.",5,doyen9,1768667109,Đen,NaN,"giao hàngg nhanh, dùngg khá ổn shop có tư vấn. mua được giá rẻe.",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
1,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:Redmi Active 5\nChất lượng sản phẩm:Mình đánh giá sau\n\nRedmi Active 5.\nDo hết hàng nên mình đợi kh...,5,dthang92,1765961178,Bạc,NaN,đúng với mô tả:redmi active 5 chất lượng sản phẩm:mình đánh giá sau redmi active 5. do hết hàng nên mình đợi khá lâu...,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",5,p*****f,1767692199,Đen,NaN,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
3,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:ok\nChất lượng sản phẩm:ok\n\nsp khá ổn trong tầm giá,5,b*****0,1764553050,Bạc,NaN,đúng với mô tả:ok chất lượng sản phẩm:ok sp khá ổn trong tầm giá,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
4,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Giao hàng nhanh chóng. Hình ảnh và video mang tính chất nhận xu.,5,d*****7,1769928670,Đen,NaN,giao hàng nhanh chóng. hình ảnh và video mang tính chất nhận xu.,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0

In [18]:
ASPECT_MODELS = {
    "BATTERY": "van105/absa-visfd-final-battery",    
    "CAMERA": "van105/absa-visfd-final-camera",
    "SCREEN": "van105/absa-visfd-final-screen",
    "PERFORMANCE": "van105/absa-visfd-final-performance",
    "PRICE": "van105/absa-visfd-final-price",
    "DESIGN": "van105/absa-visfd-final-design",
    "FEATURES": "van105/absa-visfd-final-features",
    "STORAGE": "van105/absa-visfd-final-storage",
    "SERANDACC": "van105/absa-visfd-final-serandacc",
    "GENERAL": "van105/absa-visfd-final-general",
}

ASPECTS = list(ASPECT_MODELS.keys())

LABEL_MAP = {
    "LABEL_0": "negative",
    "LABEL_1": "neutral",
    "LABEL_2": "positive",
    "LABEL_3": "not_mentioned"
}

device = 0 if torch.cuda.is_available() else -1
print("Device:", "GPU" if device == 0 else "CPU")

Device: GPU

In [19]:
TEXT_COL = "review_text_clean"

if TEXT_COL not in reviews.columns:
    raise ValueError(f"Không tìm thấy cột {TEXT_COL}. Hãy kiểm tra file shopee_reviews_processed.csv")

reviews[TEXT_COL] = reviews[TEXT_COL].fillna("").astype(str)
reviews = reviews[reviews[TEXT_COL].str.strip() != ""].copy()

# Test nhanh thì đặt SAMPLE_N = 500 hoặc 1000.
# Chạy thật thì để SAMPLE_N = None.
SAMPLE_N = None

if SAMPLE_N is not None:
    reviews_run = reviews.sample(n=min(SAMPLE_N, len(reviews)), random_state=42).copy()
else:
    reviews_run = reviews.copy()

texts = reviews_run[TEXT_COL].tolist()

print("Số review chạy ABSA:", len(texts))
display(reviews_run.head())

Số review chạy ABSA: 8992

,shop,shop_id,item_id,product_name,product_url,review_text,review_star,author_username,ctime,model_name,liked_count,review_text_clean,sentiment_by_star,review_star_group,shop_clean,brand,product_type,product_name_norm,storage_options,canonical_product_name,canonical_product_id
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Giao hàngg nhanh, dùngg khá ổn shop có tư vấn. Mua được giá rẻe.",5,doyen9,1768667109,Đen,NaN,"giao hàngg nhanh, dùngg khá ổn shop có tư vấn. mua được giá rẻe.",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
1,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:Redmi Active 5\nChất lượng sản phẩm:Mình đánh giá sau\n\nRedmi Active 5.\nDo hết hàng nên mình đợi kh...,5,dthang92,1765961178,Bạc,NaN,đúng với mô tả:redmi active 5 chất lượng sản phẩm:mình đánh giá sau redmi active 5. do hết hàng nên mình đợi khá lâu...,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",5,p*****f,1767692199,Đen,NaN,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
3,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:ok\nChất lượng sản phẩm:ok\n\nsp khá ổn trong tầm giá,5,b*****0,1764553050,Bạc,NaN,đúng với mô tả:ok chất lượng sản phẩm:ok sp khá ổn trong tầm giá,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0
4,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Giao hàng nhanh chóng. Hình ảnh và video mang tính chất nhận xu.,5,d*****7,1769928670,Đen,NaN,giao hàng nhanh chóng. hình ảnh và video mang tính chất nhận xu.,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0

In [20]:
def predict_aspect_labels(texts, model_name, batch_size=32):
    clf = pipeline(
        "text-classification",
        model=model_name,
        tokenizer=model_name,
        device=device,
        truncation=True,
        max_length=256
    )

    results = clf(
        texts,
        batch_size=batch_size,
        truncation=True,
        max_length=256
    )

    labels = [LABEL_MAP.get(r["label"], r["label"]) for r in results]
    scores = [float(r["score"]) for r in results]
    return labels, scores

In [21]:
for aspect, model_name in ASPECT_MODELS.items():
    print(f"Running aspect model: {aspect} - {model_name}")

    labels, scores = predict_aspect_labels(
        texts=texts,
        model_name=model_name,
        batch_size=32
    )

    reviews_run[f"{aspect}_label"] = labels
    reviews_run[f"{aspect}_score"] = scores

print("ABSA labeling done!")
display(reviews_run.head())

Running aspect model: BATTERY - van105/absa-visfd-final-battery

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: CAMERA - van105/absa-visfd-final-camera

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: SCREEN - van105/absa-visfd-final-screen

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: PERFORMANCE - van105/absa-visfd-final-performance

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: PRICE - van105/absa-visfd-final-price

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: DESIGN - van105/absa-visfd-final-design

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: FEATURES - van105/absa-visfd-final-features

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: STORAGE - van105/absa-visfd-final-storage

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: SERANDACC - van105/absa-visfd-final-serandacc

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

Running aspect model: GENERAL - van105/absa-visfd-final-general

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

ABSA labeling done!

,shop,shop_id,item_id,product_name,product_url,review_text,review_star,author_username,ctime,model_name,liked_count,review_text_clean,sentiment_by_star,review_star_group,shop_clean,brand,product_type,product_name_norm,storage_options,canonical_product_name,canonical_product_id,BATTERY_label,BATTERY_score,CAMERA_label,CAMERA_score,SCREEN_label,SCREEN_score,PERFORMANCE_label,PERFORMANCE_score,PRICE_label,PRICE_score,DESIGN_label,DESIGN_score,FEATURES_label,FEATURES_score,STORAGE_label,STORAGE_score,SERANDACC_label,SERANDACC_score,GENERAL_label,GENERAL_score
0,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Giao hàngg nhanh, dùngg khá ổn shop có tư vấn. Mua được giá rẻe.",5,doyen9,1768667109,Đen,NaN,"giao hàngg nhanh, dùngg khá ổn shop có tư vấn. mua được giá rẻe.",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0,not_mentioned,0.995345,not_mentioned,0.998347,not_mentioned,0.998367,not_mentioned,0.655152,positive,0.989975,not_mentioned,0.989388,not_mentioned,0.992178,not_mentioned,0.981758,positive,0.979298,positive,0.963133
1,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:Redmi Active 5\nChất lượng sản phẩm:Mình đánh giá sau\n\nRedmi Active 5.\nDo hết hàng nên mình đợi kh...,5,dthang92,1765961178,Bạc,NaN,đúng với mô tả:redmi active 5 chất lượng sản phẩm:mình đánh giá sau redmi active 5. do hết hàng nên mình đợi khá lâu...,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0,not_mentioned,0.994835,not_mentioned,0.998393,not_mentioned,0.998397,not_mentioned,0.924487,not_mentioned,0.994480,not_mentioned,0.990795,not_mentioned,0.992861,not_mentioned,0.980908,positive,0.984082,not_mentioned,0.766656
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,"Đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",5,p*****f,1767692199,Đen,NaN,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0,positive,0.987058,not_mentioned,0.997803,positive,0.993490,positive,0.500992,not_mentioned,0.993416,not_mentioned,0.966689,not_mentioned,0.964750,not_mentioned,0.979391,not_mentioned,0.962153,not_mentioned,0.796031
3,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Đúng với mô tả:ok\nChất lượng sản phẩm:ok\n\nsp khá ổn trong tầm giá,5,b*****0,1764553050,Bạc,NaN,đúng với mô tả:ok chất lượng sản phẩm:ok sp khá ổn trong tầm giá,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0,not_mentioned,0.995419,not_mentioned,0.998119,not_mentioned,0.997977,not_mentioned,0.784671,neutral,0.983588,not_mentioned,0.989339,not_mentioned,0.992419,not_mentioned,0.975948,not_mentioned,0.948107,positive,0.981065
4,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",https://shopee.vn/product/340431675/28914299334,Giao hàng nhanh chóng. Hình ảnh và video mang tính chất nhận xu.,5,d*****7,1769928670,Đen,NaN,giao hàng nhanh chóng. hình ảnh và video mang tính chất nhận xu.,positive,5 sao,xiaomiofficialstore,Xiaomi,smartwatch_band,redmi watch 5 active màn hình lcd 2 inch l nghe gọi bluetooth kháng nước 5atm +140 chế độ thể thao,NaN,redmi watch 5 active,169.0,not_mentioned,0.994967,not_mentioned,0.996516,positive,0.990741,not_mentioned,0.595632,not_mentioned,0.994159,not_mentioned,0.977919,not_mentioned,0.987055,not_mentioned,0.980923,positive,0.548022,not_mentioned,0.953851

In [22]:
reviews_run.to_csv("/kaggle/working/shopee_reviews_absa_labeled.csv", index=False, encoding="utf-8-sig")
print("Saved: /kaggle/working/shopee_reviews_absa_labeled.csv")

Saved: /kaggle/working/shopee_reviews_absa_labeled.csv

In [23]:
base_cols = [
    "shop",
    "shop_id",
    "item_id",
    "product_name",
    "review_star",
    TEXT_COL
]

# Giữ thêm canonical nếu đã có trong reviews_processed
for col in ["canonical_product_name", "canonical_product_id", "product_type"]:
    if col in reviews_run.columns and col not in base_cols:
        base_cols.append(col)

long_rows = []

for aspect in ASPECTS:
    temp = reviews_run[base_cols + [f"{aspect}_label", f"{aspect}_score"]].copy()
    temp["aspect"] = aspect
    temp["sentiment"] = temp[f"{aspect}_label"]
    temp["confidence"] = temp[f"{aspect}_score"]
    temp = temp.drop(columns=[f"{aspect}_label", f"{aspect}_score"])
    long_rows.append(temp)

review_aspect_long = pd.concat(long_rows, ignore_index=True)

review_aspect_mentioned = review_aspect_long[
    review_aspect_long["sentiment"] != "not_mentioned"
].copy()

print("review_aspect_long:", review_aspect_long.shape)
print("review_aspect_mentioned:", review_aspect_mentioned.shape)

display(review_aspect_mentioned.head())

review_aspect_long: (89920, 12)
review_aspect_mentioned: (24536, 12)

,shop,shop_id,item_id,product_name,review_star,review_text_clean,canonical_product_name,canonical_product_id,product_type,aspect,sentiment,confidence
2,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",5,"đồng hồ thông minh đa chức năng, màn hình đẹp, pin bền, theo dõi sức khỏe chính xác rất ok nhé!",redmi watch 5 active,169.0,smartwatch_band,BATTERY,positive,0.987058
7,xiaomiofficialstore,340431675,28914299334,"Đồng hồ thông minh Redmi Watch 5 Active | Màn hình LCD 2"" l Nghe gọi Bluetooth | Kháng nước 5ATM | +140 chế độ thể thao",5,sản phẩm tốt. bao bì hộp đầy đủ. giá rẻ hơn so với mua ở điện máy xanh thế giới di động. lúc đầu sản phẩm có tiếng a...,redmi watch 5 active,169.0,smartwatch_band,BATTERY,positive,0.978209
33,xiaomiofficialstore,340431675,48656445603,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",5,"chất lượng sản phẩm:đẹp tính năng nổi bật:ok đúng với mô tả:ổn tải game thấy nóng máy, chắc mới ngày đầu, sạc cũng n...",poco x8 pro 5g,153.0,phone,BATTERY,positive,0.942437
55,xiaomiofficialstore,340431675,48656445603,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",5,"hiệu năng:tác cụ bt thì pin đến tối ,còn chiến game nặng như genshin thì nhanh bù lại sạc 100w 1tiếng là đầy mượt vớ...",poco x8 pro 5g,153.0,phone,BATTERY,positive,0.936383
56,xiaomiofficialstore,340431675,48656445603,"(Pre-order) Điện thoại POCO X8 Pro 5G (8+256GB| 8+512GB| 12+512GB) | Màn 6.59"" 1,5K 120Hz | D8500U | 50MP",5,tính năng nổi bật:ngon đúng với mô tả:đúng chất lượng sản phẩm:ok đáng mua nhe cho đt poco x8 pro chơi game ngon pin...,poco x8 pro 5g,153.0,phone,BATTERY,positive,0.986911

In [24]:
review_aspect_long.to_csv("/kaggle/working/review_aspect_long.csv", index=False, encoding="utf-8-sig")
review_aspect_mentioned.to_csv("/kaggle/working/review_aspect_mentioned.csv", index=False, encoding="utf-8-sig")

print("Saved:")
print("/kaggle/working/review_aspect_long.csv")
print("/kaggle/working/review_aspect_mentioned.csv")

Saved:
/kaggle/working/review_aspect_long.csv
/kaggle/working/review_aspect_mentioned.csv

In [25]:
sentiment_summary = (
    review_aspect_mentioned
    .groupby(["shop_id", "item_id", "aspect", "sentiment"])
    .size()
    .reset_index(name="count")
)

sentiment_pivot = sentiment_summary.pivot_table(
    index=["shop_id", "item_id", "aspect"],
    columns="sentiment",
    values="count",
    fill_value=0
).reset_index()

for col in ["negative", "neutral", "positive"]:
    if col not in sentiment_pivot.columns:
        sentiment_pivot[col] = 0

sentiment_pivot["total_mentions"] = (
    sentiment_pivot["negative"] +
    sentiment_pivot["neutral"] +
    sentiment_pivot["positive"]
)

sentiment_pivot = sentiment_pivot[sentiment_pivot["total_mentions"] > 0].copy()

sentiment_pivot["positive_rate"] = sentiment_pivot["positive"] / sentiment_pivot["total_mentions"]
sentiment_pivot["negative_rate"] = sentiment_pivot["negative"] / sentiment_pivot["total_mentions"]
sentiment_pivot["neutral_rate"] = sentiment_pivot["neutral"] / sentiment_pivot["total_mentions"]

sentiment_pivot["aspect_sentiment_score"] = (
    sentiment_pivot["positive"] - sentiment_pivot["negative"]
) / sentiment_pivot["total_mentions"]

product_info_cols = [
    "shop", "shop_id", "item_id", "product_name",
    "canonical_product_name", "canonical_product_id",
    "product_type", "brand", "current_price", "rating",
    "sold_count_num", "monthly_sold_num", "product_url"
]
product_info_cols = [c for c in product_info_cols if c in products.columns]

product_aspect_summary = sentiment_pivot.merge(
    products[product_info_cols].drop_duplicates(["shop_id", "item_id"]),
    on=["shop_id", "item_id"],
    how="left"
)

display(product_aspect_summary.head())

,shop_id,item_id,aspect,negative,neutral,positive,total_mentions,positive_rate,negative_rate,neutral_rate,aspect_sentiment_score,shop,product_name,canonical_product_name,canonical_product_id,product_type,brand,current_price,rating,sold_count_num,monthly_sold_num,product_url
0,65589552,1622955655,BATTERY,0.0,1.0,0.0,1.0,0.000000,0.00000,1.000000,0.000000,samsung_official_store,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh",máy hút bụi dạng hộp samsung,119.0,home_appliance,SAMSUNG,1546720.0,4.889132,10000.0,130.0,https://shopee.vn/product/65589552/1622955655
1,65589552,1622955655,CAMERA,0.0,0.0,1.0,1.0,1.000000,0.00000,0.000000,1.000000,samsung_official_store,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh",máy hút bụi dạng hộp samsung,119.0,home_appliance,SAMSUNG,1546720.0,4.889132,10000.0,130.0,https://shopee.vn/product/65589552/1622955655
2,65589552,1622955655,DESIGN,22.0,6.0,82.0,110.0,0.745455,0.20000,0.054545,0.545455,samsung_official_store,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh",máy hút bụi dạng hộp samsung,119.0,home_appliance,SAMSUNG,1546720.0,4.889132,10000.0,130.0,https://shopee.vn/product/65589552/1622955655
3,65589552,1622955655,FEATURES,11.0,13.0,134.0,158.0,0.848101,0.06962,0.082278,0.778481,samsung_official_store,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh",máy hút bụi dạng hộp samsung,119.0,home_appliance,SAMSUNG,1546720.0,4.889132,10000.0,130.0,https://shopee.vn/product/65589552/1622955655
4,65589552,1622955655,GENERAL,0.0,6.0,205.0,211.0,0.971564,0.00000,0.028436,0.971564,samsung_official_store,"Máy hút bụi dạng hộp Samsung 360W VC18M2120SB/SV - Turbine Không Xoắn Tóc, màu Xanh",máy hút bụi dạng hộp samsung,119.0,home_appliance,SAMSUNG,1546720.0,4.889132,10000.0,130.0,https://shopee.vn/product/65589552/1622955655

In [26]:
product_aspect_summary.to_csv("/kaggle/working/product_aspect_summary.csv", index=False, encoding="utf-8-sig")
print("Saved: /kaggle/working/product_aspect_summary.csv")

Saved: /kaggle/working/product_aspect_summary.csv

In [27]:
ASPECT_WEIGHTS = {
    "GENERAL": 1.0,
    "PRICE": 1.3,
    "PERFORMANCE": 1.3,
    "BATTERY": 1.2,
    "SCREEN": 1.1,
    "CAMERA": 1.0,
    "DESIGN": 0.9,
    "FEATURES": 1.0,
    "STORAGE": 0.8,
    "SERANDACC": 1.1
}

sentiment_pivot["aspect_weight"] = sentiment_pivot["aspect"].map(ASPECT_WEIGHTS).fillna(1.0)
sentiment_pivot["weighted_score"] = (
    sentiment_pivot["aspect_sentiment_score"] *
    sentiment_pivot["aspect_weight"] *
    sentiment_pivot["total_mentions"]
)

product_absa_score = (
    sentiment_pivot
    .groupby(["shop_id", "item_id"])
    .agg(
        absa_weighted_sum=("weighted_score", "sum"),
        absa_weight_sum=("total_mentions", "sum"),
        total_aspect_mentions=("total_mentions", "sum"),
        avg_positive_rate=("positive_rate", "mean"),
        avg_negative_rate=("negative_rate", "mean"),
        avg_neutral_rate=("neutral_rate", "mean")
    )
    .reset_index()
)

product_absa_score["absa_score_raw"] = (
    product_absa_score["absa_weighted_sum"] / product_absa_score["absa_weight_sum"]
)

product_absa_score["absa_score"] = (
    (product_absa_score["absa_score_raw"] + 1) / 2
) * 100

display(product_absa_score.head())

,shop_id,item_id,absa_weighted_sum,absa_weight_sum,total_aspect_mentions,avg_positive_rate,avg_negative_rate,avg_neutral_rate,absa_score_raw,absa_score
0,65589552,1622955655,756.4,869.0,869.0,0.790459,0.050434,0.159107,0.870426,93.521289
1,65589552,2103555064,97.0,96.0,96.0,0.947685,0.009259,0.043056,1.010417,100.520833
2,65589552,24523897801,23.7,64.0,64.0,0.774828,0.200821,0.024351,0.370313,68.515625
3,65589552,25073898651,8.4,44.0,44.0,0.647810,0.308120,0.044071,0.190909,59.545455
4,65589552,26728758506,983.7,1072.0,1072.0,0.864282,0.062412,0.073306,0.917631,95.881530

In [28]:
product_absa_score.to_csv("/kaggle/working/product_absa_score.csv", index=False, encoding="utf-8-sig")
print("Saved: /kaggle/working/product_absa_score.csv")

Saved: /kaggle/working/product_absa_score.csv